### ISSUE TITLE
reCAPTCHA Problem

### ISSUE THREAD

**Issue by cfasnacht** [ltb-project/self-service-password#145]
Hi
I have the following problem:
"The reCAPTCHA was not entered correctly. Try again."
Only with version: self-service-password-1.0-2.el7.noarch
with self-service-password-0.9-1.el5.noarch everything works fine again.
Do you have any ideas?

Thanks a lot
Christian

**Comment by plewin** [comment]
Hi @cfasnacht, please check your log, when this error occurs extra details on the error are logged.
Also enable $debug = true while debugging to not miss any potentially useful information.

**Comment by cfasnacht** [comment]
crazy fast reply! Thanks! :-)

I enabled debugging and found the following error in the httpd log: /var/log/httpd/xxx-ssl_error_log <==
[Thu Aug 31 15:53:28 2017] [error] [client x.x.x.x] Bad reCAPTCHA attempt with user test01, referer: https://example.com/
[Thu Aug 31 15:53:28 2017] [error] [client x.x.x.x] reCAPTCHA error: invalid-json, referer: https://example.com/

**Comment by plewin** [comment]
Outch invalid-json,

If it worked in 0.9 i believe you have to reconfigure the recaptcha

In SSP 0.9 the recaptcha lib is very old and deprecated.
In SSP 1.0 the recaptcha is new.

Please reconfigure your recaptcha and see if it works
https://github.com/ltb-project/self-service-password/blob/v1.0/conf/config.inc.php#L222
https://ltb-project.org/documentation/self-service-password/1.0/config_recaptcha

**Comment by coudot** [comment]
See also https://github.com/ltb-project/self-service-password/issues/126

Should be solved in 1.1

**Comment by plewin** [comment]
@coudot OP is not concerned by #126 because SSP 0.9 recaptcha worked for him.
I believe he gets this problem because the recaptcha lib in ssp 0.9 and >= 1.0 are different. I will not be surprised if new api keys are required.

**Comment by cfasnacht** [comment]
@plewin 
I tried to set the recaptcha setting to the following:
$recaptcha_theme = "light"; # dark / light
$recaptcha_type = "image"; # audio / image
$recaptcha_size = "normal"; # compact / normal
Still the same error.

@coudot 
How does this relate to my issue? We don't use a proxy?

**Comment by plewin** [comment]
@cfasnacht 
Please connect to google recaptcha https://www.google.com/recaptcha and get new api keys.
For
```
$recaptcha_publickey = "xxxx";
$recaptcha_privatekey = "xxxx";
```
The API key you use in SSP 0.9 are, I believe, no longer compatible with the new recaptcha embedded in SSP 1.0.

**Comment by cfasnacht** [comment]
@plewin What kind of type do I need, I had: Site Type V2, and created new api keys for invisible. I have the same problem. Working with 0.9 and not with 1.0.

**Comment by plewin** [comment]
You had Site Type V2 with SSP 0.9 ? :v
So it should work....

To understand why you get "invalid-json" I suggest this



Find in this file on your system.
https://github.com/ltb-project/self-service-password/blob/v1.0/lib/vendor/ReCaptcha/ReCaptcha.php#L95

And between these 2 lines

```
$rawResponse = $this->requestMethod->submit($params);
return Response::fromJson($rawResponse);
```

add 

`var_dump($rawResponse);`

It will look like this : 

```
$rawResponse = $this->requestMethod->submit($params);
var_dump($rawResponse); // remove after the test
return Response::fromJson($rawResponse);
```

And then try again the captcha and see if you have a detailed message

**Comment by coudot** [comment]
I was thinking this was the same issue as https://stackoverflow.com/questions/30106668/nocaptcha-returning-error-invalid-json#30848193

Using curl might solve the problem, and this is now possible in SSP with the PR https://github.com/ltb-project/self-service-password/pull/131

**Comment by plewin** [comment]
@coudot 
yea, you are right, it is not related to issue https://github.com/ltb-project/self-service-password/issues/126 but possibly to https://github.com/ltb-project/self-service-password/issues/130

recaptcha in SSP 0.9 use sockets (fsockopen), recaptcha SSP in 1.0 use file_get_contents which depends on allow_url_fopen=1, if allow_url_fopen=0 recaptcha will break on 0.9->1.0 upgrade

these 2 issues have the same fix PR https://github.com/ltb-project/self-service-password/pull/131 yes

@cfasnacht please check if allow_url_fopen=0 on your php installation, if it the case, either set allow_url_fopen=1, hack ssp code, or wait for SSP 1.1

**Comment by cfasnacht** [comment]
You are right if I change:
allow_url_fopen = On to allow_url_fopen = Off in my php.ini it works.
I will wait for 1.1
Thanks a lot!

**Comment by plewin** [comment]
You mean if you change allow_url_fopen = Off to allow_url_fopen = On in your php.ini SSP 1.0 works right (not the opposite) ?
