### ISSUE TITLE
Problem with 1.1

### ISSUE THREAD

**Issue by cfasnacht** [ltb-project/self-service-password#153]
Hi
I updated to version 1.1 all seems to work fine, I enter the old, new passwords, fill out the captscha. The new site loads and only shows Self service password in a green background. But the password is not changed.
The only log enty I see is:
x.x.x.x - - [05/Oct/2017:10:41:35 +0200] "POST / HTTP/1.1" 500 1049 "https://passwd.x.x/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0" 0 747912
Thanks
Christian

**Comment by plewin** [comment]
Hi @cfasnacht, have you activated $debug = true to have more log entries ?

**Comment by cfasnacht** [comment]
I have already activated debug in the output above with: $debug = true;

**Comment by plewin** [comment]
Hum, it is very strange that there is a 500 without details on the error.

On what platform are you ? Are you using the rpm packages on a centos ?

Also can you please provide a copy of the page source code when your problem appears. It will help me guess approximately where your problem is located in the code.
Reproduce the bug -> Control + U to show the page source -> Control + A to select all -> Copy -> Paste in Gist https://gist.github.com/ & create secret gist -> Copy the link here

**Comment by cfasnacht** [comment]
I use Centos 6.9 with this rpm: https://ltb-project.org/rpm/6/noarch/self-service-password-1.1-1.el6.noarch.rpm
I hope its ok if I paste the page source here, it is not long.

<html lang="en">
<head>
    <title>Self service password</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="LDAP Tool Box" />
    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="css/bootstrap-theme.min.css" />
    <link rel="stylesheet" type="text/css" href="css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="css/self-service-password.css" />
    <link href="images/favicon.ico" rel="icon" type="image/x-icon" />
    <link href="images/favicon.ico" rel="shortcut icon" />
</head>
<body>

<div class="container">

<div class="panel panel-success">
<div class="panel-body">

<div class="title alert alert-success text-center"><h1>Self service password</h1></div>

**Comment by plewin** [comment]
Hum, you are upgrading from 0.9 right ?

Can you try to disable the captcha and try again to see if the problem comes from the captcha feature ?
`$use_recaptcha = false;`

Also, Are you using the new $recaptcha_request_method option to solve your previous issue https://github.com/ltb-project/self-service-password/issues/145 ?

**Comment by cfasnacht** [comment]
You are right I indeed updated  from 0.9.1 and I have the same issue with captschas disabled, do you have an idea what the problem could be?

**Comment by plewin** [comment]
Unfortunately I have no idea why you get an error and why there is no log while $debug = true.
I hoped it was because of the captcha feature because there is very little changes in code between 0.9 and 1.1 when changing a password using the standard form, except for the captcha.

You would mind posting your config.inc.php in a secret gist and post the link here so I can review it and use it to try to reproduce the issue ?
Please change/erase the values of $ldap_bindpw, $keyphrase, $recaptcha_privatekey before posting it.

Also to reproduce the issue, I need more details on your php environment.

Create this file \usr\share\self-service-password\info.php with this content
`<?php phpinfo(); ?>`
Go to your usual url for self service password + /info.php instead of /index.php then Ctrl + A to select all, copy and paste in an other gist and post the link here please

**Comment by cfasnacht** [comment]
https://gist.github.com/cfasnacht/d4d03c1277a1811c34981fca99af8965
Everything I changed I replaced with xxx, so you can I easly see what modified.
Thanks a lot for the awesome support!

**Comment by plewin** [comment]
I reproduced a similar issue, can you please, install mcrypt + restart httpd and retry :
```
sudo yum install mcrypt
sudo service httpd restart
```

if it stills does not work, can you please post in a gist your phpinfo details see my previous comment  how to https://github.com/ltb-project/self-service-password/issues/153#issuecomment-334435995

**Comment by cfasnacht** [comment]
It still does not work with mcrypt installed.
The info.php page that is  returned is empty.
The error in the log file is:
script '/usr/share/self-service-password/info.php' not found or unable to stat
The file exists with the following permissions:
ll /usr/share/self-service-password/info.php
-rw-r--r-- 1 apache apache 20  5. Okt 17:18 /usr/share/self-service-password/info.php

ll /usr/share/self-service-password/info.php
-rw-r--r-- 1 apache apache 20  5. Okt 17:18 /usr/share/self-service-password/info.php

**Comment by plewin** [comment]
Hi @cfasnacht,

Your apache is scrict with the script's permissions.

`chmod +x /usr/share/self-service-password/info.php`

should solve the "not found or unable to stat" problem

**Comment by cfasnacht** [comment]
-rwxr-xr-x 1 apache apache 20 12. Okt 14:32 /usr/share/self-service-password/info.php
cat /usr/share/self-service-password/info.php 
<?php phpinfo(); ?>

log: [12/Oct/2017:14:46:46 +0200] "GET /info.php HTTP/1.1" 200 - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0" 0 25690
There is no longer an error but apache returns an empty page.

**Comment by cfasnacht** [comment]
You are write:
#/etc/php.ini
disable_functions =  "phpinfo, pcntl_exec, show_source"

**Comment by cfasnacht** [comment]
You are write:
#/etc/php.ini
disable_functions = "phpinfo, pcntl_exec, show_source"

I commented out this line, here is the info.php site:
https://gist.github.com/cfasnacht/c605a3f76acecae482e6e2a20d142b23

With the self service password I still have the same issue

Again thanks for your help! :-)

**Comment by plewin** [comment]
Outch,

Your installation use php 5.3. We do not test on this version anymore, we test starting from 5.4.
I am not sure that SSP 1.1 is compatible with php 5.3. I think so because the changes breaking compatibility with 5.3 were postponed to SSP 1.2. but it is possible that we left a piece of code breaking with php 5.3.

I recommend you to upgrade your php version.
https://secure.php.net/supported-versions.php

According to your phpinfo details, your log file is located at /var/log/httpd/php5.log
With $debug = true, you should see an the error at the end of the file. I guess a "syntax error" or "undefined function" confirming a php compatibility problem.

**Comment by plewin** [comment]
Hi @cfasnacht , do you still need assistance ?

**Comment by plewin** [comment]
I am closing this thread because of inactivity. Please reopen it, or a new one, if you still need assistance.

**Comment by cfasnacht** [comment]
We moved this to CentOs 7.4 with php 5.4, now everything works!
Thanks!
